 {{-- <div style="page-break-after: always;"></div> --}}
 <title>PERFORMANCE REPORT</title>
 <img src="https://www.pup.edu.ph/about/images/PUPLogo.png" style="width: 70.4pt; height: 70.6pt; float: left" alt="image">
  <img src="https://www.transparenttextures.com/patterns/asfalt-light.png" style="width: 70.4pt; height: 70.6pt; float: right;" alt="image">

<center>
<p style='margin-top:5.0pt;margin-right:0cm;margin-bottom:0pt;margin-left:0cm;font-size:15px;font-family:"Franklin Gothic Medium",sans-serif;color:black;'>Polytechnic University of the Philippines</p>
  <p style='margin-top:5.0pt;margin-right:0cm;margin-bottom:0pt;margin-left:0cm;font-size:15px;font-family:"Franklin Gothic Medium",sans-serif;color:black;'>PUP Support </p>
   <p style='margin-top:5.0pt;margin-right:0cm;margin-bottom:0pt;margin-left:0cm;font-size:15px;font-family:"Franklin Gothic Medium",sans-serif;color:black;'>Report Generated By The System.</p>
</center>
 <p style='margin-top:20.0pt;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;text-align:center;font-size:25px;font-family:"Franklin Gothic Medium",sans-serif;color:#006666;'> PERFORMANCE REPORT</p>
       
<table style="border: none;width:100.0%;border-collapse: collapse;" summary="Header layout table">
    <tbody>
        <tr>
            <td style="width: 100.1pt;border-top: none;border-bottom: none;border-left: none;border-image: initial;border-right: 1.5pt solid white;background: rgb(0, 102, 102);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;color:white;font-weight:normal;'><span style='font-family:"Franklin Gothic Medium",sans-serif;'>Report Date</span></h2>
            </td>
            <td style="width: 100.05pt;border-top: none;border-bottom: none;border-left: none;border-image: initial;border-right: 1.5pt solid white;background: rgb(0, 102, 102);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;color:white;font-weight:normal;'><span style='font-family:"Franklin Gothic Medium",sans-serif;'>Position</span></h2>
            </td>
            <td style="width: 150.85pt;border: none;background: rgb(0, 102, 102);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;color:white;font-weight:normal;'><span style='font-family:"Franklin Gothic Medium",sans-serif;'>Prepared By</span></h2>
            </td>
        </tr>
        <tr>
            <td style="width: 100.1pt;border-top: 1.5pt solid white;border-left: none;border-bottom: none;border-right: 1.5pt solid white;background: rgb(229, 234, 238);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'><span style="color:black;"><?php echo date('F d, Y');?></span></p>
            </td>
            <td style="width: 100.05pt;border-top: 1.5pt solid white;border-left: none;border-bottom: none;border-right: 1.5pt solid white;background: rgb(229, 234, 238);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'><span style="color:black;">
                    @if(session('is_admin'))Admin 
                    @else Agent
                    @endif
            </span></p>
            </td>
            <td style="width: 150.85pt;border-right: none;border-bottom: none;border-left: none;border-image: initial;border-top: 1.5pt solid white;background: rgb(229, 234, 238);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'><span style="color:black;"> @foreach($created_by as $val)
            {{ $val->user_fname }} {{ $val->user_lname }}
          @endforeach</span></p>
            </td>
        </tr>
    </tbody>
</table>
<table style="width:100.14%;border-collapse: collapse;border:none;" summary="Header layout table">
    <tbody>
        <tr>
            <td style="width: 576.8pt;border-top: none;border-right: none;border-left: none;border-image: initial;border-bottom: 2.25pt solid rgb(254, 222, 0);padding: 0cm;height: 36pt;vertical-align: bottom;">
                <h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:3.0pt;margin-left:0cm;font-size:16px;font-family:"Franklin Gothic Medium",sans-serif;color:#006666;'>AGENT SUMMARY</h1>
            </td>
        </tr>
        <tr>
            <td style="width:576.8pt;border:none;padding:0cm 0cm 0cm 0cm;height:10.8pt;">
                <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>&nbsp;</p>
            </td>
        </tr>
    </tbody>
</table>
<p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>Open Ticket: {{$open}}</p>
<p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>Overdue Ticket: {{$overdue}}</p>
<p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>Answered Ticket: {{$answered}}</p>
<p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>Closed Ticket: {{$closed}}</p>
<p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>SLA: {{$sla}}%</p>
<table style="width:100.14%;border-collapse: collapse;border:none;" summary="Header layout table">
    <tbody>
        <tr>
            <td style="width: 576.8pt;border-top: none;border-right: none;border-left: none;border-image: initial;border-bottom: 2.25pt solid rgb(254, 222, 0);padding: 0cm;height: 36pt;vertical-align: bottom;">
                <h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:3.0pt;margin-left:0cm;font-size:16px;font-family:"Franklin Gothic Medium",sans-serif;color:#006666;'>TICKETS ASSIGNED</h1>
            </td>
        </tr>
        <tr>
            <td style="width:576.8pt;border:none;padding:0cm 0cm 0cm 0cm;height:10.8pt;">
                <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>&nbsp;</p>
            </td>
        </tr>
    </tbody>
</table>
<table style="border: none;width:100.0%;border-collapse: collapse;" summary="Header layout table">
          <thead style="text-align:center" >
              <tr>
                 <th colspan="3" style="border-top: none;border-bottom: none;border-left: none;border-image: initial;border-right: 1.5pt solid white;background: rgb(0, 102, 102);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">  <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;color:white;font-weight:normal;'><span style='font-family:"Franklin Gothic Medium",sans-serif;'>Priority</span></h2> </th>
                  <th colspan="3" style="border-top: none;border-bottom: none;border-left: none;border-image: initial;border-right: 1.5pt solid white;background: rgb(0, 102, 102);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">  <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;color:white;font-weight:normal;'><span style='font-family:"Franklin Gothic Medium",sans-serif;'>Ticket No</span></h2>  </th>
                  <th colspan="3" style="border-top: none;border-bottom: none;border-left: none;border-image: initial;border-right: 1.5pt solid white;background: rgb(0, 102, 102);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">  <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;color:white;font-weight:normal;'><span style='font-family:"Franklin Gothic Medium",sans-serif;'>Created at</span></h2> </th>
                 
                  <th colspan="3" style="border-top: none;border-bottom: none;border-left: none;border-image: initial;border-right: 1.5pt solid white;background: rgb(0, 102, 102);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">  <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;color:white;font-weight:normal;'><span style='font-family:"Franklin Gothic Medium",sans-serif;'>Status</span></h2> </th>

                  <th colspan="3" style="border-top: none;border-bottom: none;border-left: none;border-image: initial;border-right: 1.5pt solid white;background: rgb(0, 102, 102);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">  <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;color:white;font-weight:normal;'><span style='font-family:"Franklin Gothic Medium",sans-serif;'>Due Date</span></h2></th>
                  
                  
              </tr>
          </thead>
          <tbody>
            

            @foreach($assigned as $row)
            <tr>
                <td colspan="3"style="width: 144pt;border-top: 1.5pt solid white;border-left: none;border-bottom: none;border-right: 1.5pt solid white;background: rgb(229, 234, 238);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                    
                    <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>{{ $row->priority_name }}</p>
                </td>
                <td colspan="3" style="width: 144pt;border-top: 1.5pt solid white;border-left: none;border-bottom: none;border-right: 1.5pt solid white;background: rgb(229, 234, 238);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                    
                    <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>{{ $row->ticket_no }}</p>
                </td>
               
                <td colspan="3" style="width: 144pt;border-top: 1.5pt solid white;border-left: none;border-bottom: none;border-right: 1.5pt solid white;background: rgb(229, 234, 238);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                    
                    <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>{{ $row->created_at }}</p>
                </td>

                <td colspan="3" style="width: 144pt;border-top: 1.5pt solid white;border-left: none;border-bottom: none;border-right: 1.5pt solid white;background: rgb(229, 234, 238);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                    
                    <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>{{ $row->ticket_status }}</p>
                </td>
                <td colspan="3" style="width: 144pt;border-top: 1.5pt solid white;border-left: none;border-bottom: none;border-right: 1.5pt solid white;background: rgb(229, 234, 238);padding: 0cm 5.4pt;height: 16.55pt;vertical-align: top;">
                    
                    <p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>{{ $row->ticket_date }}</p>
                </td>

            </tr>
            @endforeach
            
        </tbody>                                 
    </table>

<p style='margin-top:2.0pt;margin-right:0cm;margin-bottom:2.0pt;margin-left:0cm;font-size:13px;font-family:"Franklin Gothic Book",sans-serif;'>&nbsp;</p>